- name: Add docker apt signing key
  become: true
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
    keyring: /etc/apt/trusted.gpg.d/docker.gpg
  when: ansible_distribution == "Ubuntu"

- name: Add docker repository into sources list
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ deb_architecture.stdout }}] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    filename: docker
  when: ansible_distribution == "Ubuntu"  

- name: Install Docker
  become: true
  ansible.builtin.package:
    name:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io 
      - docker-compose-plugin
    state: latest
    update_cache: yes