# - name: Download golang
#   become: true
#   get_url:
#     url: https://go.dev/dl/go1.18.2.darwin-amd64.pkg
#     dest: /usr/local/go
#   when: ansible_distribution == "MacOSX"

- name: Install golang
  community.general.homebrew:
    name: go
    state: present
  when: ansible_distribution == "MacOSX"  