- name: Install Idea
  become: true
  community.general.snap:
    name: intellij-idea-ultimate
    classic: yes
  when: ansible_distribution == "Ubuntu"  

- name: Install Idea
  community.general.homebrew_cask:
    name: intellij-idea
    state: present
  when: ansible_distribution == "MacOSX"    