- name: Install mac specific cask
  community.general.homebrew_cask:
    name: 
      - iterm2
      - warp
      - maccy
      - sourcetree
      - spectacle
      - skitch
    state: present
  when: ansible_distribution == "MacOSX"