- name: "Install nodejs"
  apt:
    update_cache: yes
    name: nodejs
    state: present
- community.general.homebrew:
    name: nodejs
    state: present
    update_homebrew: yes
    upgrade_all: yes

    
