# - name: "Install nvm"
#   community.general.homebrew:
#     name: nvm
#     state: present
#   when: ansible_distribution == "MacOSX"
- name: "nvm"
  shell: >
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.39.1/install.sh | bash
  args:
    executable: /bin/bash
    chdir: "{{ ansible_env.HOME }}"
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
  when: ansible_distribution == "MacOSX"
  
- name: Setup .profile
  ansible.builtin.lineinfile:
    path: ~/.profile
    line: source ~/.nvm/nvm.sh # This will make sure Node is on the user's PATH
    create: yes
  when: ansible_distribution == "MacOSX"

- name: "node"
  shell: >
    . {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install {{ item }}
  args:
    executable: /bin/bash
    chdir: "{{ ansible_env.HOME }}"
    creates: "{{ ansible_env.HOME }}/.nvm/versions/{{ item }}"
  loop:
    - node
  when: ansible_distribution == "MacOSX"
    
