- name: Install other packages
  become: true
  ansible.builtin.package:
    name:
      - curl
      - wget
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: Install other packages
  community.general.homebrew:
    name:
      - curl
      - hurl
      - wget
      - jq
      - fx
      - yh
      - colima
      - kcat
      - minikube
      - vegeta
      - watch
      - gnu-tar
      - ctop
      - jo
      - jid
      - jsonnet
    state: present
  when: ansible_distribution == "MacOSX"      