- name: Add hashicorp apt signing key
  become: true
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present
    keyring: /etc/apt/trusted.gpg.d/hashicorp.gpg
  when: ansible_distribution == "Ubuntu"

- name: Add hashicorp repository into sources list
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ deb_architecture.stdout }}] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    state: present
    filename: hashicorp
  when: ansible_distribution == "Ubuntu"  

- name: Install Terraform
  become: true
  ansible.builtin.package:
    name:
      - terraform
    state: latest
    update_cache: yes