- name: setup zsh
  community.general.homebrew:
    name: zsh, fzf, ripgrep, bat, fd, findutils jq
    state: present
  when: ansible_distribution == "MacOSX"  
  
- name: Set zsh as default
  ansible.builtin.command: chsh -s /bin/zsh
  when: ansible_distribution == "MacOSX"  
