- name: Install cask
  community.general.homebrew_cask:
    name: iterm2
    state: present
  when: ansible_distribution == "MacOSX"

- name: Install zsh
  community.general.homebrew:
    name: zsh
    state: present
  when: ansible_distribution == "MacOSX"  

- name: Install oh-my-zsh
  run_once: true
  ansible.builtin.shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)" || exit 0
  when: ansible_distribution == "MacOSX"
  
- name: Set login shell of user {{ ansible_env.USER }} to `/bin/zsh` with `usermod`
  ansible.builtin.command: usermod --shell /bin/zsh {{ ansible_env.USER }} || exit 0
  become: true
  changed_when: false
# - name: Setup zsh
#   run_once: true
#   ansible.builtin.shell: chsh -s /bin/zsh || exit 0
  when: ansible_distribution == "MacOSX"

- name: setup zshrc
  ansible.builtin.copy:
    src: files/home/.zshrc
    dest: "{{ ansible_env.HOME }}/.zshrc"
