---
# tasks file for base
- name: Upgrade apt packages
  become: true
  apt:
    upgrade: yes
  when: ansible_distribution == "Ubuntu"
  
- name: Upgrade brew
  community.general.homebrew:
    upgrade_all: yes
    update_homebrew: yes
  when: ansible_distribution == "MacOSX"
   
